name: "Node.js Cleanup"
author: "ryohidaka <39184410+ryohidaka@users.noreply.github.com>"
description: "A GitHub Action that cleanup Node.js template configures."

inputs:
  description:
    required: false
    description: "The description of the project."

  version:
    required: false
    default: "0.0.0"
    description: "The version of the project. If not provided, the default is '0.0.0'."

  email:
    required: false
    description: "The email address to be used in the project."

  bugs-url:
    required: false
    description: "The URL where the project's bugs are tracked. If not provided, the default is the issues page of the repository (e.g., 'https://github.com/username/repo/issues')."

  homepage:
    required: false
    description: "The URL of the project's homepage. If not provided, the default is the readme page of the repository (e.g., 'https://github.com/username/repo#readme')."

  remove-license:
    required: false
    default: false
    description: "A boolean value that indicates whether to remove the license. The default is false."

  excluded:
    required: false
    description: "Comma-separated list of file or directory paths to remove."

  template-dir:
    required: false
    description: "The path to the project's template directory. If not provided, the default template directory will be used."

  remove-template-dir:
    required: false
    default: false
    description: "A boolean value indicating whether to remove the template directory. The default is false."

  placeholders:
    required: false
    default: '{"name": "%NAME%", "description": "%DESCRIPTION%", "author": "%AUTHOR%"}'

  commit-user-name:
    required: false
    default: "GitHub Actions"
    description: "The username for the commit. If not provided, the default is 'GitHub Actions'."

  commit-user-email:
    required: false
    default: "actions@github.com"
    description: "The user email for the commit. If not provided, the default is 'actions@github.com'."

  commit-message:
    required: false
    default: "Template cleanup"
    description: "The commit message. If not provided, the default is 'Template cleanup'."

  dryrun:
    required: false
    default: false
    description: "Execute the process, but do not push the commit at the end."

runs:
  using: "composite"
  steps:
    # Check out current repository
    - name: Fetch Sources
      uses: actions/checkout@v4

    - name: Install jq
      run: sudo apt-get install jq
      shell: bash

    - name: Set Variables
      run: bash sh/set-variables.sh
      shell: bash
      env:
        INPUT_DESCRIPTION: ${{ inputs.description }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_EMAIL: ${{ inputs.email }}
        INPUT_BUGS_URL: ${{ inputs.bugs-url }}
        INPUT_HOMEPAGE: ${{ inputs.homepage }}

    - name: Replace Placeholder
      run: bash sh/replace/placeholder.sh
      shell: bash
      env:
        INPUT_PLACEHOLDERS: ${{ inputs.placeholders }}

    - name: Replace template files
      if: ${{ inputs.template-dir != '' }}
      run: bash sh/replace/template-file.sh
      shell: bash
      env:
        INPUT_TEMPLATE_DIR: ${{ inputs.template-dir }}
        INPUT_REMOVE_TEMPLATE_DIR: ${{ inputs.remove-template-dir }}

    - name: Replace package.json
      run: bash sh/replace/package-json.sh
      shell: bash

    - name: Remove LICENSE
      if: ${{ inputs.remove-license == 'true' }}
      run: bash sh/remove/license.sh
      shell: bash

    - name: Remove excluded files
      if: ${{ inputs.excluded != '' }}
      run: bash sh/remove/files.sh
      shell: bash
      env:
        INPUT_REMOVE_FILES: ${{ inputs.excluded }}

    # Commit modified files
    - name: Commit files
      run: |
        git config --local user.email "${{ inputs.commit-user-email }}"
        git config --local user.name "${{ inputs.commit-user-name }}"
        git add .
        git commit -m "${{ inputs.commit-message }}"
      shell: bash

    # Push
    - name: Push
      if: ${{ inputs.dryrun == 'false' }}
      run: git push origin main
      shell: bash
