name: "Node.js Cleanup"
author: "ryohidaka <39184410+ryohidaka@users.noreply.github.com>"
description: "A GitHub Action that cleanup Node.js template configures."

runs:
  using: "composite"
  steps:
    # Check out current repository
    - name: Fetch Sources
      uses: actions/checkout@v4
