name: Test Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          description: "hogehoge"
          version: "0.1.0"
          email: "39184410+ryohidaka@users.noreply.github.com"
          remove-license: true

      - name: Install jq
        run: sudo apt-get install jq
        shell: bash

      - name: Check package.json
        run: |
          DESCRIPTION=$(jq -r .description package.json)
          if [ "$DESCRIPTION" != "hogehoge" ]; then
            echo "::error:: Description in package.json is not 'hogehoge'. It is '$DESCRIPTION'."
            exit 1
          fi
